CREATE TABLE [Account].[DirectDebit]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[Amount] MONEY NOT NULL,
	[FromAccountId] UNIQUEIDENTIFIER NOT NULL,
	[ToAccountId] UNIQUEIDENTIFIER NOT NULL,
	[StartDate] DATETIMEOFFSET NOT NULL,
	[LastRunTimestamp] DATETIMEOFFSET NULL,
	[Frequency] INT NOT NULL
)
